import { spawn } from 'child_process';
import fs from 'fs-extra';
import path from 'path';
import { EXECUTION_LIMITS, REQUEST_LIMITS } from '../config/constants.js';
import { isSafeManagedBinaryPath } from './binary-artifacts.js';
import { trackChildProcessMetrics } from './process-metrics.js';

function normalizeArgs(args) {
  if (!Array.isArray(args)) {
    return [];
  }

  return args
    .slice(0, REQUEST_LIMITS.args)
    .map((arg) => (typeof arg === 'string' ? arg : String(arg)));
}

export async function runBinary(binaryPath, args = [], input = '') {
  const startTime = Date.now();
  const resolvedBinaryPath = path.resolve(binaryPath || '');
  const safeBinaryPath = isSafeManagedBinaryPath(resolvedBinaryPath) ? resolvedBinaryPath : null;

  if (!safeBinaryPath) {
    return {
      stdout: '',
      stderr: 'Invalid binary path. Only temporary binaries generated by this service can be executed.',
      exitCode: 126,
      executionTime: 0,
      peakMemoryBytes: null
    };
  }

  const exists = await fs.pathExists(safeBinaryPath);
  if (!exists) {
    return {
      stdout: '',
      stderr: `Binary not found: ${safeBinaryPath}`,
      exitCode: 127,
      executionTime: 0,
      peakMemoryBytes: null
    };
  }

  const normalizedArgs = normalizeArgs(args);
  const normalizedInput = typeof input === 'string' ? input : String(input ?? '');

  let timedOut = false;
  let outputLimitHit = false;
  let outputBytes = 0;
  let stdout = '';
  let stderr = '';
  let exitCode = 0;
  let peakMemoryBytes = null;

  try {
    const result = await new Promise((resolve, reject) => {
      const child = spawn(safeBinaryPath, normalizedArgs, { stdio: 'pipe' });
      const metrics = trackChildProcessMetrics(child);
      const timer = setTimeout(() => {
        timedOut = true;
        child.kill('SIGKILL');
      }, EXECUTION_LIMITS.timeoutMs);

      child.stdout.on('data', (chunk) => {
        outputBytes += chunk.length;
        stdout += chunk.toString();
        if (!outputLimitHit && outputBytes > EXECUTION_LIMITS.outputBytes) {
          outputLimitHit = true;
          child.kill('SIGKILL');
        }
      });

      child.stderr.on('data', (chunk) => {
        outputBytes += chunk.length;
        stderr += chunk.toString();
        if (!outputLimitHit && outputBytes > EXECUTION_LIMITS.outputBytes) {
          outputLimitHit = true;
          child.kill('SIGKILL');
        }
      });

      child.on('error', (err) => {
        clearTimeout(timer);
        reject(err);
      });

      child.on('close', async (code, signal) => {
        clearTimeout(timer);
        peakMemoryBytes = await metrics.stop();
        resolve({ code, signal });
      });

      if (normalizedInput) {
        child.stdin.write(normalizedInput);
      }
      child.stdin.end();
    });

    exitCode = result.code ?? (timedOut ? 124 : outputLimitHit ? 122 : 1);

    if (timedOut && !stderr) {
      stderr = `Execution timed out after ${EXECUTION_LIMITS.timeoutMs}ms`;
    }

    if (outputLimitHit && !stderr) {
      stderr = `Execution output exceeded ${EXECUTION_LIMITS.outputBytes} bytes`;
    }
  } catch (err) {
    stderr = err instanceof Error ? err.message : 'Execution failed';
    exitCode = 1;
  } finally {
    if (safeBinaryPath) {
      await fs.remove(safeBinaryPath).catch(() => {});
    }
  }

  return {
    stdout,
    stderr,
    exitCode,
    executionTime: Date.now() - startTime,
    peakMemoryBytes
  };
}
